### ISSUE TITLE
An Detail Installation NEED

### ISSUE THREAD

**Issue by haozhangcn** [zhujiang73/caffe-windows-opencl#1]
SHALL You give an detail installation?

Thanks!

**Comment by subshall** [comment]
我也是没办法安装成功。好难搞啊

**Comment by zhujiang73** [comment]
1.   install   msys2 : http://www.msys2.org
2.   install   amd  opencl   sdk :  https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk/
3.    win10  cmd  console :
    md  build
    cd  build 
    cmake -G "MinGW Makefiles"  ..  -DCMAKE_INSTALL_PREFIX="c:\mingw"
    mingw32-make  install

中文版的说明在这里  ：http://blog.sina.com.cn/s/blog_9c88eb910102x0we.html
